AppIntegrador/Models/Objetivo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objetivo()
        {
            this.AccionDeMejora = new HashSet<AccionDeMejora>();
            this.Seccion = new HashSet<Seccion>();
        }
    
        public int codPlan { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string nombTipoObj { get; set; }
        public Nullable<int> codPlantilla { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionDeMejora> AccionDeMejora { get; set; }
        public virtual PlanDeMejora PlanDeMejora { get; set; }
        public virtual PlantillaObjetivo PlantillaObjetivo { get; set; }
        public virtual TipoObjetivo TipoObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccion> Seccion { get; set; }
    }
}

AppIntegrador/Controllers/ObjetivoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppIntegrador.Models;

namespace AppIntegrador.Controllers
{
    public class ObjetivoController : Controller
    {
        private DataIntegradorEntities db = new DataIntegradorEntities();

        // GET: Objetivo
        public ActionResult Index()
        {
            var objetivo = db.Objetivo.Include(o => o.PlantillaObjetivo).Include(o => o.TipoObjetivo);
            return View(objetivo.ToList());
        }

        // GET: Objetivo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objetivo objetivo = db.Objetivo.Find(id);
            if (objetivo == null)
            {
                return HttpNotFound();
            }
            return View(objetivo);
        }

        // GET: Objetivo/Create
        public ActionResult Create()
        {
            ViewBag.codPlantilla = new SelectList(db.PlantillaObjetivo, "codigo", "nombre");
            ViewBag.nombTipoObj = new SelectList(db.TipoObjetivo, "nombre", "nombre");
            return View("_crearObjetivo");
        }

        // POST: Objetivo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "codPlan,nombre,descripcion,fechaInicio,fechaFin,nombTipoObj,codPlantilla")] Objetivo objetivo)
        {
            if (ModelState.IsValid)
            {
                db.Objetivo.Add(objetivo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.codPlantilla = new SelectList(db.PlantillaObjetivo, "codigo", "nombre", objetivo.codPlantilla);
            ViewBag.nombTipoObj = new SelectList(db.TipoObjetivo, "nombre", "nombre", objetivo.nombTipoObj);
            return View(objetivo);
        }

        // GET: Objetivo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objetivo objetivo = db.Objetivo.Find(id);
            if (objetivo == null)
            {
                return HttpNotFound();
            }
            ViewBag.codPlantilla = new SelectList(db.PlantillaObjetivo, "codigo", "nombre", objetivo.codPlantilla);
            ViewBag.nombTipoObj = new SelectList(db.TipoObjetivo, "nombre", "nombre", objetivo.nombTipoObj);
            return View(objetivo);
        }

        // POST: Objetivo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "codPlan,nombre,descripcion,fechaInicio,fechaFin,nombTipoObj,codPlantilla")] Objetivo objetivo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(objetivo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.codPlantilla = new SelectList(db.PlantillaObjetivo, "codigo", "nombre", objetivo.codPlantilla);
            ViewBag.nombTipoObj = new SelectList(db.TipoObjetivo, "nombre", "nombre", objetivo.nombTipoObj);
            return View(objetivo);
        }

        // GET: Objetivo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objetivo objetivo = db.Objetivo.Find(id);
            if (objetivo == null)
            {
                return HttpNotFound();
            }
            return View(objetivo);
        }

        // POST: Objetivo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Objetivo objetivo = db.Objetivo.Find(id);
            db.Objetivo.Remove(objetivo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppIntegrador/Controllers/ObjetivosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using AppIntegrador.Models;
using System.IO;
using AppIntegrador.Utilities;

using AppIntegrador.Controllers.PlanesDeMejoraBI;

namespace AppIntegrador.Controllers
{
    public class ObjetivosController : Controller
    {
        private DataIntegradorEntities db = new DataIntegradorEntities();
        private readonly IPerm permissionManager = new PermissionManager();
        private PlanesDeMejoraUtil util = new PlanesDeMejoraUtil();

        public ObjetivosController() { }
        public ObjetivosController(DataIntegradorEntities db = null, PlanesDeMejoraUtil util = null)
        {
            if(db != null)
            {
                this.db = db;
            }
            if(util != null)
            {
                this.util = util;
            }
        }


        [HttpPost]
        public ActionResult AnadirObjetivos(List<Objetivo> objetivos)
        {
            string result = util.getView(PartialView("_TablaObjetivos", objetivos), this.ControllerContext);
            return Json(new { error = true, message = result });
        }

        [HttpPost]
        public ActionResult ObtenerSecciones(List<String> FormularioSeleccionado)
        {
            List<Formulario_tiene_seccion> parejas = new List<Formulario_tiene_seccion>();
            if(FormularioSeleccionado != null && FormularioSeleccionado.Count > 0)
            {
                foreach (var codigo in FormularioSeleccionado)
                {
                    foreach (var pareja in db.Formulario_tiene_seccion.Where(x => x.FCodigo.Equals(codigo) ) )
                    {
                        parejas.Add(pareja);
                    }
                }
            }
            string result = util.getView(PartialView("_AnadirSecciones", parejas), this.ControllerContext);
            return Json(new { error = true, message = result });
        }

        //se usa
        [HttpGet]
        public PartialViewResult listaDeObjetivos(int id)
        {
            ViewBag.IdPlan = id;
            IEnumerable<AppIntegrador.Models.Objetivo> objetivos = db.Objetivo.Where(o => o.codPlan == id);
            //return PartialView("_listarObjetivos", objetivos);
            return PartialView("_TablaObjetivosLista", objetivos);
        }
        public string TablaSeccionesAsociadas(int id, string objt)
        {

            IEnumerable<string> CodigosSecciones = db.ObtenerSeccionesAsociadasAObjetivo(id, objt);
            List<AppIntegrador.Models.Seccion> Secciones = new List<Seccion>();

            foreach (var cod in CodigosSecciones)
            {
                Secciones.Add(db.Seccion.Find(cod));
            }

            return util.getView(PartialView("_ListaSecciones", Secciones), this.ControllerContext);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppIntegrador/Views/Objetivos/CrearAsociado.cshtml
@model AppIntegrador.Models.Objetivo

@{
    ViewBag.Title = "CrearAsociado";
}

<h2>CrearAsociado</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @ViewBag.user_id
        @ViewBag.codigo
        <h4>Objetivo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo_O, "Tipo_O", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tipo_O", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tipo_O, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppIntegrador/Views/Objetivos/Create.cshtml
@model AppIntegrador.Models.Objetivo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Objetivo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.codPlan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codPlan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.codPlan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombTipoObj, "nombTipoObj", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("nombTipoObj", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.nombTipoObj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codPlantilla, "codPlantilla", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("codPlantilla", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.codPlantilla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppIntegrador/Views/Objetivos/Delete.cshtml
@model AppIntegrador.Models.Objetivo

@{
    ViewBag.Title = "Delete";
    Layout = null;
    string idModal = "borrarObjetivoPDM";
    idModal += Model.codPlan.ToString();
    idModal += Model.descripcion;
    idModal += Model.nombre;
    idModal += Model.TipoObjetivo;

    <script>
        console.log(@idModal);
    </script>
}

<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@idModal">
    Borrar
</button>

<!-- Modal -->
<div class="modal fade" id="@idModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edición del Objetivo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @*Inicio del cuerpo del modal*@

                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    Seguro que desea borrar este objetivo. Esta acción es irreversible.
                </div>

                <div>
                    <h4>Objetivo</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.nombre)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.descripcion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.TipoObjetivo.nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.TipoObjetivo.nombre)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.fechaInicio)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.fechaInicio)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.fechaFin)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.fechaFin)
                        </dd>
                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()


                        /*
                         Modificado por: Johan Córdoba
                         Historia a la que pertenece: MOS-1.2 "agregar, modificar, borrar y consultar los objetivos de un plan de mejora"
                         Cambio la funcionalidad del boton para que no refresque toda la vista
                         y solo cierre el modal. Además esto tambien permite que en las vistas parciales
                         an cancelar la creación de un plan de mejora vuelva a esta vista y no a la de
                         index de acciones de mejora.

                        */
                        <div class="botonCentrado">
                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-danger" />
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                @*@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })*@
                            </div>
                        </div>
                    }
                </div>

                @*Fin del cuerpo del modal*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Salir</button>
                <button type="button" class="btn btn-primary">Guardar cambios</button>
            </div>
        </div>
    </div>
</div>

AppIntegrador/Views/Objetivos/Edit.cshtml
@model AppIntegrador.Models.Objetivo

@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="modal-body">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <h4>Objetivo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.codPlan)
        @Html.HiddenFor(model => model.nombre)

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">

                    <div class="row">
                        <div class="col-md-8">

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.codPlan, htmlAttributes: new { @class = "control-label" })
                    <div class="row">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.codPlan, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                            @Html.ValidationMessageFor(model => model.codPlan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.nombTipoObj, htmlAttributes: new { @class = "control-label" })
                    <div class="row">
                        <div class="col-md-8">
                            @Html.DropDownList("nombTipoObj", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.nombTipoObj, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label" })
                    <div class="row">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.fechaFin, htmlAttributes: new { @class = "control-label" })
                    <div class="row">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.fechaFin, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fechaFin, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", maxlength = "50", disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.descripcion, new { @class = "form-control", rows = "4", maxlength = "250", style = "resize:vertical", placeholder = "Máximo 250 caracteres" })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">


                @*
                    Modificado por: Johan Córdoba
                    Historia a la que pertenece: MOS-1.2 "agregar, modificar, borrar y consultar los objetivos de un plan de mejora"
                    Cambio la funcionalidad del boton para que no refresque toda la vista
                    y solo cierre el modal. Además esto tambien permite que en las vistas parciales
                    an cancelar la creación de un plan de mejora vuelva a esta vista y no a la de
                    index de acciones de mejora.
                *@

                <div class="botonCentrado">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    @*@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })*@
                </div>
            </div>
        </div>

    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

</div>

AppIntegrador/Views/Objetivos/Index.cshtml
@model IEnumerable<AppIntegrador.Models.Objetivo>
@{
    ViewBag.Title = "Index";
}

<div>
    @*
        Modificado por: Johan Córdoba
        Historia a la que pertenece: MOS-1.2 "agregar, modificar, borrar y consultar los objetivos de un plan de mejora"
        Cambio para que se adapte a la vista parcial de planes de mejoras.
    *@

    <div class="row">
        <div class="col-md-8">
            <h2 class="impText">Objetivos</h2>
        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-2">
            <br />
            @*
                Modificado por: Johan Córdoba
                Historia a la que pertenece: MOS-1.2 "agregar, modificar, borrar y consultar los objetivos de un plan de mejora"
                Cambio para que redireccione al create de objetivo
            *@
            @Html.ActionLink("Nuevo Objetivo", "Create", "Objetivos", new { id = ViewBag.idPlan }, new { @class = "modal-link btn btn-Nuevo col-md-12" })
        </div>

    </div>

    @if (Model.Count() == 0)
    {
        <div class="centeredText">
            <p>
                Aún no se han creado objetivos en el plan seleccionado
            </p>
        </div>
    }
    else
    {
        <table class="table">
            <tr class="EncabezadoTabla">
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fechaInicio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.fechaFin)
                </th>
                <th>
                    Opciones
                </th>
            </tr>

            @foreach (var obj in Model)
            {
                <tbody id="dataOb">
                    <tr class="FilaTablasPlanesDeMejora" onclick="clickObjetivo(@obj.codPlan, `@obj.nombre`);">
                        <td class="TablasNombre">
                            @Html.DisplayFor(modelItem => obj.nombre)
                        </td>
                        <td class="TablasDescripcion">
                            @Html.DisplayFor(modelItem => obj.descripcion)
                        </td>
                        <td class="TablasFecha">
                            @Html.DisplayFor(modelItem => obj.fechaInicio)
                        </td>
                        <td class="TablasFecha">
                            @Html.DisplayFor(modelItem => obj.fechaFin)
                        </td>
                        <td class="TablasOpciones">
                            <div class="col-md-6">
                                @Html.ActionLink("Editar", "Edit", "Objetivos", new { plan = obj.codPlan, title = obj.nombre }, new { @class = "modal-link btn btn-primary" })
                            </div>
                            <div class="col-md-6">
                                @Html.ActionLink("Borrar", "Delete", "Objetivos", new { plan = obj.codPlan, title = obj.nombre }, new { @class = "modal-link btn btn-danger" })
                            </div>
                            @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                        </td>
                    </tr>
                </tbody>
            }

        </table>
    }


    <hr />
</div>

<script>
    $("#dataOb tr").click(function () {
        var selected = $(this).hasClass("highlight2");
        $("#dataOb tr").removeClass("highlight2");
        if (!selected)
            $(this).addClass("highlight2");
    });
</script>

AppIntegrador/Views/Objetivos/_AnadirSecciones.cshtml
@model IEnumerable<AppIntegrador.Models.Formulario_tiene_seccion>
@{
    ViewBag.Title = "Añadir Secciones";
    var totalSecciones = 0;
}

<h4> Añadir secciones al objetivo </h4>

<table id="TablaSeleccionarSeccion" class="table table-striped table-bordered table-sm " cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>

            </th>
            <th>
                Codigo del formulario
            </th>
            <th>
                Codigo de la seccion
            </th>
        </tr>
    </thead>
    <thead>
        @foreach (var pair in Model)
        {
            <tr>
                <td>
                    <input type="checkbox"
                           id="pr(@totalSecciones)"
                           name="checkBoxSeccionObjetivo"
                           class="SectionCheckbox"
                           value="@pair.SCodigo" />
                           @*onclick="seleccionaCheckBoxGen(this, 'secc', 'scodigo', cantidadSecc)" />*@
                </td>

                <td>
                    @pair.FCodigo
                </td>
                <td>
                    @pair.SCodigo
                </td>
            </tr>
            totalSecciones += 1;
        }
    </thead>
</table>