AppIntegrador/Controllers/PermissionsController.cs
using AppIntegrador.Models;
using AppIntegrador.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using AppIntegrador.Models.Metadata;
using System.Threading.Tasks;

namespace AppIntegrador.Controllers
{
    /*TAM-3.1, 3.2, 3.4, 3.5, 3.6, 3.7, 4.1: Controlador que implementa la funcionalidad de la página de administración de permisos y perfiles. */
    public class PermissionsController : Controller
    {
        private DataIntegradorEntities db;

        private readonly IPerm permissionManager;

        public PermissionsController()
        {
            db = new DataIntegradorEntities();
            permissionManager = new PermissionManager();
        }

        public PermissionsController(DataIntegradorEntities db)
        {
            this.db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            /*Solo se puede acceder a este método si el usuario tiene un perfil con los permisos apropiados.*/
            if (!permissionManager.IsAuthorized(Permission.VER_PERMISOS_Y_PERFILES))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("Index", "Home");
            }
            PermissionsViewHolder model = new PermissionsViewHolder();

            return View(model);
        }

        /*TAM-3.3-1, 3.7-1.*/
        /*Método que lanza a la página de selección de perfil. Todos los usuarios tienen acceso a esto.*/
        [HttpGet]
        public ActionResult SeleccionarPerfil()
        {
            return View(new ConfigViewHolder());
        }
        /*Fin TAM-3.3.1, 3.7.1*/


        /// <summary>Este método guarda la selección de perfil, carrera y énfasis que el usuario haya seleccionado.</summary>
        /// <param name="ListaPerfiles">Código del perfil que el usuario seleccionó.</param>
        /// <param name="ListaCarreras">Código de la carrera que el usuario seleccionó.</param>
        /// <param name="ListaEnfasis">Código del énfasis que el usuario seleccionó.</param>
        /// <returns>ActionResult que redirige a la página Home/Index.</returns>
        [HttpPost]
        public ActionResult GuardarSeleccion(string ListaPerfiles, string ListaCarreras, string ListaEnfasis)
        {
            CurrentUser.setUserProfile(ListaPerfiles);
            CurrentUser.setUserMajor(ListaCarreras);
            CurrentUser.setUserEmphasis(ListaEnfasis);

            TempData["sweetalertmessage"] = "Cambios guardados";
            return RedirectToAction("Index", "Home");
        }
        /*Fin TAM-3.7.1*/

        /*TAM 3.4-1*/
        /// <summary>Este método guarda la combinación de selección de perfil, carrera, énfasis, personas y permisos.</summary>
        /// <param name="model">Objeto que contiene los datos de la selección.</param>
        /// <param name="isUser">Booleano para indicar si se están guardando datos de asignación de perfiles a personas
        /// o de permisos a perfiles.</param>
        /// <returns>ActionResult que recarga los datos de la página de administración de perfiles.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(PermissionsViewHolder model)
        {
            if (!permissionManager.IsAuthorized(Permission.EDITAR_PERMISOS_Y_PERFILES))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("../Home/Index");
            }

            int codPerfil = model.PerfilesSeleccionados;
            string perfil = model.Perfiles[codPerfil].NombrePerfil;
            string codCarrera = model.CarrerasSeleccionadas;
            string codEnfasis = model.EnfasisSeleccionados;
            List<Persona> Personas = model.Personas;
            List<Permiso> Permisos = model.Permisos;

            if ((perfil == null) || (codCarrera == null) || (codEnfasis == null))
            {
                TempData["alertmessage"] = "Algo salió mal. Intente de nuevo.";
                return RedirectToAction("Index", "Home");
            }

            if (permissionManager.IsAuthorized(Permission.ASIGNAR_PERFILES_USUARIOS))
            {
                //Guarda las asignaciones de un perfil en una carrera y un enfasis a los usuarios
                for (int i = 0; i < Personas.Count; ++i)
                {
                    db.AgregarUsuarioPerfil(Personas[i].Correo, perfil, codCarrera, codEnfasis, Personas[i].HasProfileInEmph);
                }
            }

            if(permissionManager.IsAuthorized(Permission.ASIGNAR_PERMISOS_PERFILES))
            {
                //Guarda las asignaciones de permisos a un perfil en una carrera y un enfasis
                for (int i = 0; i < Permisos.Count; ++i)
                {
                    db.AgregarPerfilPermiso(perfil, Permisos[i].Id, codCarrera, codEnfasis, Permisos[i].ActiveInProfileEmph);
                }
            }
            ViewBag.resultmessage = "Los cambios han sido guardados";
            return View(model);
        }
        /* Fin TAM 3.4-1.*/

        /*TAM-3.2*/
        /// <summary>Este método Se llama cuando se selecciona un énfasis en la página, para cargar los checkboxes según la configuración seleccionada.</summary>
        /// <param name="profileCode">Código del perfil seleccionado.</param>
        /// <param name="profileName">Nombre del perfil seleccionado.</param>
        /// <param name="majorCode">Código de la carrera seleccionada.</param>
        /// <param name="emphCode">Código del énfasis de la carrera seleccionado.</param>
        /// <returns>Objeto JsonResult que contiene los datos de los checkboxes en este formato, para ser renderizados por la vista.</returns>
        [HttpPost]
        public JsonResult CargarCheckboxes(string profileCode, string profileName, string majorCode, string emphCode)
        {
            if ((profileCode == null) || (profileName == null) || (majorCode == null) || (emphCode == null)) {
                TempData["alertmessage"] = "Algo salió mal. Intente de nuevo.";
                return Json(new { persons = "", permissions = "" });
            }
            PermissionsViewHolder model = new PermissionsViewHolder();
            // Obtener nombre de Perfil y Énfasis

            // Actualizar los checkboxes con la selección de énfasis.

            ObjectParameter tienePerfil = new ObjectParameter("tienePerfil", typeof(bool));
            ObjectParameter tieneActivo = new ObjectParameter("tieneActivo", typeof(bool));
            // Para revisar si el usuario tiene todos esos perfiles
            int total;
            int correct;

            // Revisa los checks de las personas
            foreach (Persona persona in model.Personas)
            {
                total = 0;
                correct = 0;

                ++total;
                // Se asume una sola carrera y un solo énfasis
                db.TienePerfilEnElEnfasis(persona.Correo, profileName, majorCode, emphCode, tienePerfil);

                if ((bool)tienePerfil.Value)
                {
                    // Si tiene el perfil asignado, aumente contador
                    ++correct;
                }

                // Tiene al menos un perfil
                if (correct > 0)
                {
                    // Tiene todos los perfiles
                    if (total == correct)
                    {
                        persona.HasProfileInEmph = true;
                    }
                }
            }

            // Revisa los checks de los permisos
            foreach (Permiso permiso in model.Permisos)
            {
                total = 0;
                correct = 0;

                ++total;
                // Se asume una sola carrera y un solo énfasis
                db.TienePermisoActivoEnEnfasis(permiso.Id, profileName, majorCode, emphCode, tieneActivo);

                if ((bool)tieneActivo.Value)
                {
                    // Si está activado en el perfil, aumente contador
                    ++correct;
                }


                // Activo en al menos un perfil
                if (correct > 0)
                {
                    // Activo en todos los perfiles
                    if (total == correct)
                    {
                        permiso.ActiveInProfileEmph = true;
                    }
                }
            }
            return Json(new { persons = PermissionManagerViewBuilder.ListPersonProfiles(model.Personas), permissions = PermissionManagerViewBuilder.ListProfilePermissions(model.Permisos) });
        }
        /*Fin TAM-3.2*/

        /*TAM-6.3-1.*/
        /// <summary>Este método envía a la vista los énfasis de la carrera que se haya seleccionado en formato JSON.</summary>
        /// <param name="value">Código de la carrera seleccionada.</param>
        /// <returns>Objeto JsonResult que contiene los datos de los énfasis de la carrera este formato, para ser renderizados por la vista.</returns>
        [HttpGet]
        public JsonResult CargarEnfasisDeCarrera(string value)
        {
            List<string> enfasis = new List<string>();
            using (var context = new DataIntegradorEntities())
            {
                /*Utiliza una función almacenada para obtener los énfasis que tiene una determinada carrera.*/
                var listaEnfasis = from Carrera in db.EnfasisXCarrera(value)
                                   select Carrera;
                foreach (var codigoEnfasis in listaEnfasis)
                {
                    string nombreEnfasis = db.Enfasis.Find(value, codigoEnfasis.codEnfasis).Nombre;

AppIntegrador/Views/Permissions/SeleccionarPerfil.cshtml
<!--Página que muestra la funcionalidad de la historia TAM-3.7-1: que un usuario pueda configurar el perfil, la carrera y el énfasis
    con los que está trabajando en el sistema.-->
@model AppIntegrador.Models.ConfigViewHolder

@{
    ViewBag.Title = "Index";
}

@Styles.Render("~/Content/users&profiles")

<div class="container col-8 p-5 border" style="background-color: #fbfbfb">
    <div class="row" style="display:flex; padding-left:15px; ">
        <div class="column" style="flex:50%;">
            <h2>
                Seleccionar perfil de trabajo
            </h2>
        </div>
    </div>
    <p>Actualmente usted está trabajando con el perfil: @AppIntegrador.Models.CurrentUser.getUserProfile()</p>
    <p>Carrera: @Html.DisplayFor(model => model.NombreCarrera)</p>
    <p>Enfasis: @Html.DisplayFor(model => model.NombreEnfasis)</p>
    
    @using (Html.BeginForm("GuardarSeleccion", "Permissions", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
    {
        <div class="row" style="display:flex; padding-left:15px; ">
            <div class="col-md-4 pl-0" style="flex:50%;">
                @Html.Label("Seleccione perfil")
                <br />
                @Html.DropDownListFor(model => model.ListaPerfiles, Model.PerfilesSeleccionables, new { @class = "form-control", @required = "required" })
                <br />
            </div>

            <div class="col-md-4" style="flex:50%;">
                @Html.Label("Seleccione carrera")
                <br />
                @Html.DropDownListFor(model => model.ListaCarreras, Enumerable.Empty<SelectListItem>(), new { @class = "form-control", @required = "required" })
                <br />
            </div>

            <div class="col-md-4" style="flex:50%;">
                @Html.Label("Seleccione énfasis")
                <br />
                @Html.DropDownListFor(model => model.ListaEnfasis, Enumerable.Empty<SelectListItem>(), new { @class = "form-control", @required = "required" })
                <br />
            </div>
        </div>

        <button type="submit" class="btn-azulUCR">Seleccionar</button>
        @Html.ActionLink("Cancelar", "Index", "Home", new object { }, new { @class = "btn-blancoUCR" })
    }

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<script>
    /*Función que invoca a la función que carga las carreras de un usuario, según el perfil que haya escogido.*/
    $("#ListaPerfiles").on("change", function () {
        cargarCarreras($("#ListaPerfiles option:selected").val());
        $("#ListaEnfasis").children().remove();
        $("#ListaEnfasis").append("<option value=\"\" selected disabled hidden >Nada seleccionado</option>");
    })

    /**
     * Carga las carreras del usuario según el perfil que haya elegido.
     * <param> val Código del perfil seleccionado.
     */
    function cargarCarreras(val) {
        $.getJSON('@Url.Action("CargarCarreras", "Permissions")' + "?perfilSeleccionado=" + val, function (result) {
            $("#ListaCarreras").children().remove();

            var data = result.data;
            for (var i = 0; i < data.length; ++i) {
                var splitted = data[i].toString().split(",");
                $("#ListaCarreras").append("<option value=" + splitted[0] + ">" + splitted[1] + "</option>");
            }
            $("#ListaCarreras").append("<option value=\"\" selected disabled hidden >Nada seleccionado</option>");
        })
    }

    /*Función que invoca a la función que carga los énfasis para el usuario, según el perfil y la carrera que haya elegido.*/
    $("#ListaCarreras").on("change", function(){
        cargarEnfasisXPerfil($("#ListaCarreras option:selected").val(), $("#ListaPerfiles option:selected").val());
    })

    /**
     * Carga los énfasis en el dropdown respectivo según el perfil y la carrera que haya elegido el usuario.
     * <param> val Código de la carrera seleccionado.
     * <param> profile Código del perfil seleccionado.
     */
    function cargarEnfasisXPerfil(val, profile) {
        
        $.getJSON('@Url.Action("CargarEnfasisDeCarreraPorPerfil", "Permissions")' + "?value=" + val + "&profile=" + profile, function (result) {
            $("#ListaEnfasis").children().remove();

            var data = result.data;
            for (var i = 0; i < data.length; ++i) {
                var splitted = data[i].toString().split(",");
                $("#ListaEnfasis").append("<option value=" + splitted[0] + ">" + splitted[1] + "</option>");
            }
            $("#ListaEnfasis").append("<option value=\"\" selected disabled hidden >Nada seleccionado</option>");

        })
    }
    
</script>
<script>
    /*Evento que se dispara cuando se carga la página, para cargar los valores por defecto de los dropdowns.*/ 
    window.onload = function loadDefaultValues() {
        $.getJSON('@Url.Action("CargarDatosDefault", "Permissions")', function (result) {
                    
            var major = result.defaultMajor.split(",");
            var emphasis = result.defaultEmphasis.split(",");
            if (major.length > 1) {
                cargarCarreras(result.defaultProfile);
            }
            $('#ListaPerfiles').val(result.defaultProfile);
            $("#ListaCarreras").append("<option value=\"\" selected disabled hidden >Nada seleccionado</option>");
            $("#ListaEnfasis").append("<option value=\"\" selected disabled hidden >Nada seleccionado</option>");
                    
        })
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquerymin")
    @Scripts.Render("~/bundles/custom")
}