AppIntegrador/Models/Seccion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seccion()
        {
            this.Formulario_tiene_seccion = new HashSet<Formulario_tiene_seccion>();
            this.Responde_respuesta_con_opciones = new HashSet<Responde_respuesta_con_opciones>();
            this.Responde_respuesta_libre = new HashSet<Responde_respuesta_libre>();
            this.Seccion_tiene_pregunta = new HashSet<Seccion_tiene_pregunta>();
            this.Objetivo = new HashSet<Objetivo>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulario_tiene_seccion> Formulario_tiene_seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responde_respuesta_con_opciones> Responde_respuesta_con_opciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responde_respuesta_libre> Responde_respuesta_libre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccion_tiene_pregunta> Seccion_tiene_pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objetivo> Objetivo { get; set; }
    }
}

AppIntegrador/Models/SeccionConPreguntas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppIntegrador.Models
{
    public partial class SeccionConPreguntas
    {
        public string CodigoSeccion { get; set; }
        public string Nombre { get; set; }
        public List<PreguntaConNumeroSeccion> Preguntas { get; set; }
        public int Orden { get; set; }
        public IEnumerable<Pregunta> PreguntasNormales { get; set; }
        public bool Edicion { get; set; }
    }
}

AppIntegrador/Controllers/SeccionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppIntegrador.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data.Entity.Core.Objects;
using AppIntegrador.Utilities;

namespace AppIntegrador.Controllers
{
    public class SeccionController : Controller
    {
        private DataIntegradorEntities db = null;
        public CrearSeccionModel crearSeccion = new CrearSeccionModel();
        private readonly IPerm permissionManager = new PermissionManager();

        public SeccionController()
        {
            this.db = new DataIntegradorEntities();
        }

        public SeccionController(DataIntegradorEntities db)
        {
            this.db = db;
        }

        // GET: Seccion
        [HttpPost]
        public ActionResult ActualizarBancoSecciones(string input0, string input1, string input2)
        {
            if(!permissionManager.IsAuthorized(Permission.VER_SECCION))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("../Home/Index");
            }

            var seccion = db.Seccion;

            ViewBag.filtro = "Ninguno";
            if (input0 == null && input1 == null && input2 == null)
            {
                ViewBag.filtro = "Ninguno";
                return PartialView("_SeccionPartial", seccion.ToList());
            }
            // si se selecionó el código  
            if (input1.Length > 0)
            {
                ViewBag.filtro = "Por código: " + input1;
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return PartialView("_SeccionPartial", seccion.Where(x => x.Codigo.Contains(input1)).ToList());
            }
            // si se selecionó el enunciado 
            else if (input2.Length > 0)
            {
                ViewBag.filtro = "Nombre: " + input2;
                return PartialView("_SeccionPartial", seccion.Where(x => x.Nombre.Contains(input2)).ToList());
            }
            else
            {
                ViewBag.filtro = "Ninguno";
                return PartialView("_SeccionPartial", seccion.ToList());
            }
        }

        // GET: Seccion/Create
        public ActionResult Create()
        {
            if(!permissionManager.IsAuthorized(Permission.CREAR_SECCION))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("../Home/Index");
            }

            crearSeccion.pregunta = db.Pregunta;
            return View(crearSeccion);
        }

        // POST: Seccion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codigo,Nombre")] Seccion seccion, List<Pregunta_con_opciones_de_seleccion> preguntas)
        {
            crearSeccion.pregunta = db.Pregunta;
            if (ModelState.IsValid && seccion.Codigo.Length > 0 && seccion.Nombre.Length > 0)
            {
                if ( InsertSeccionTienePregunta(seccion, preguntas) )
                {
                    return RedirectToAction("Create");
                }
                else
                {
                    // Notifique que ocurrió un error
                    ModelState.AddModelError("Seccion.Codigo", "Código ya en uso.");
                    return View(crearSeccion);
                }
            }

            return View(crearSeccion);
        }


        // GET: Seccion
        public ActionResult Index(string input0, string input1, string input2)
        {
            var seccion = db.Seccion;

            ViewBag.filtro = "Ninguno";
            if (input0 == null && input1 == null && input2 == null)
            {
                ViewBag.filtro = "Ninguno";
                return View(seccion.ToList());
            }
            // si se selecionó el código  
            if (input1.Length > 0)
            {
                ViewBag.filtro = "Por código: " + input1;
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(seccion.Where(x => x.Codigo.Contains(input1)).ToList());
            }
            // si se selecionó el enunciado 
            else if (input2.Length > 0)
            {
                ViewBag.filtro = "Nombre: " + input2;
                return View(seccion.Where(x => x.Nombre.Contains(input2)).ToList());
            }
            else
            {
                ViewBag.filtro = "Ninguno";
                return View(seccion.ToList());
            }
        }


        // Historia RIP-BKS1
        // Se copió la función para filtrar preguntas.
        [HttpGet]
        public ActionResult Create(string input0, string input1, string input2, string input3)
        {
            if (!permissionManager.IsAuthorized(Permission.CREAR_SECCION))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("../Home/Index");
            }

            crearSeccion.pregunta = db.Pregunta;
            ViewBag.filtro = "Ninguno";
            if (input0 == null && input1 == null && input2 == null && input3 == null)
            {
                crearSeccion.pregunta = db.Pregunta.ToList();
                return View("Create", crearSeccion);
            }
            //if a user choose the radio button option as Subject  
            if (input1.Length > 0)
            {
                ViewBag.filtro = "Por código: " + input1;
                crearSeccion.pregunta = db.Pregunta.Where(x => x.Codigo.Contains(input1)).ToList();
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
            }
            else if (input2.Length > 0)
            {
                ViewBag.filtro = "Enunciado: " + input2;
                crearSeccion.pregunta = db.Pregunta.Where(x => x.Enunciado.Contains(input2)).ToList();
            }
            else if (input3.Length > 0)
            {
                var aux = "";
                switch(input3)
                {
                    case "U":
                        aux = "Selección Única";
                        break;
                    case "M":
                        aux = "Selección Múltiple";
                        break;
                    case "L":
                        aux = "Respuesta libre";
                        break;
                    case "S":
                        aux = "Sí/No/NR";
                        break;
                    case "E":
                        aux = "Escalar";
                        break;
                    default:
                        break;
                }
                ViewBag.filtro = "Tipo: " + aux;
                crearSeccion.pregunta = db.Pregunta.Where(x => x.Tipo.Contains(input3)).ToList();
            }
            else
            {
                ViewBag.filtro = "Ninguno";
                crearSeccion.pregunta = db.Pregunta.ToList();
            }
            return View("Create", crearSeccion);
        }

       
        private bool InsertSeccionTienePregunta(Seccion seccion, List<Pregunta_con_opciones_de_seleccion> preguntas)
        {
            try
            {
                if (db.AgregarSeccion(seccion.Codigo, seccion.Nombre) == 0)
                {
                    return false;
                }
            }
            catch (System.Data.Entity.Core.EntityCommandExecutionException)
            {
                return false;
            }

            if (preguntas != null)
            {
                for (int index = 0; index < preguntas.Count; ++index)
                {
                    db.AsociarPreguntaConSeccion(seccion.Codigo, preguntas[index].Codigo);
                }
            }
            return true;
        }

        [HttpGet]
        public ActionResult VistaPrevia(string id)
        {
            if (!permissionManager.IsAuthorized(Permission.VER_SECCION))
            {
                TempData["alertmessage"] = "No tiene permisos para acceder a esta página.";
                return RedirectToAction("../Home/Index");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seccion seccion = db.Seccion.Find(id);
            if (seccion == null)
            {
                return HttpNotFound();
            }
            return View(seccion);
        }

        [HttpPost]
        public ActionResult ActualizarCrearSeccion()
        {
            crearSeccion = new CrearSeccionModel();
            return PartialView("~/Views/Seccion/_CreateSeccionPartial.cshtml", crearSeccion);
        }

        public bool AgregarPreguntasASeccion(string codSeccion, List<string> codPreguntas)
        {
            if (codPreguntas != null)
            {
                for (int index = 0; index < codPreguntas.Count; ++index)
                {
                    db.AsociarPreguntaConSeccion(codSeccion, codPreguntas[index]);
                }
            }
            return true;
        }

        [HttpPost]
        public ActionResult AgregarPreguntas(string codSeccion, List<string> codPreguntas)
        {
            return Json(new { insertadoExitoso = AgregarPreguntasASeccion(codSeccion, codPreguntas) });
        }

AppIntegrador/Views/Seccion/Create.cshtml
@model AppIntegrador.Models.CrearSeccionModel

@{
    ViewBag.Title = "Crear sección";
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()

    <table class="table">
        <tr>
            <td style="width:36%">

                <div class="form-horizontal card-group">

                    <div class="card card-default">

                        <div class="card-body test2">
                            <hr />
                            <h2>Crear Sección</h2>
                            <div class="form-horizontal row">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group col-lg-5">
                                    <div>
                                        @Html.EditorFor(model => model.Seccion.Codigo, new
                                        {
                                            htmlAttributes = new
                                            {
                                                @class = "validar form-control",
                                                id = "textCode",
                                                name = "textCode",
                                                @maxlength = "8",
                                                required = "required",
                                                placeholder = "Código",
                                                rows = "5",
                                                @onkeyup = "contarCaracteres(this)"
                                            }
                                        })
                                        <div class="contador small float-right">0/8 caracteres usados</div>
                                        @Html.ValidationMessageFor(model => model.Seccion.Codigo, "", new { @style = "color:red" })
                                    </div>
                                </div>

                                <div class="form-group col-lg-7">
                                    <div>
                                        <form accept-charset="UTF-8" action="" method="POST">
                                            @Html.EditorFor(model => model.Seccion.Nombre, new
                                            {
                                                htmlAttributes = new
                                                {
                                                    @class = "validar form-control",
                                                    id = "textName",
                                                    name = "textName",
                                                    @maxlength = "250",
                                                    required = "required",
                                                    placeholder = "Nombre del formulario",
                                                    rows = "5",
                                                    @onkeyup = "contarCaracteres(this)"
                                                }
                                            })

                                            <div class="contador small float-right">0/250 caracteres usados</div>
                                            @Html.ValidationMessageFor(model => model.Seccion.Nombre, "", new { @style = "color:red" })
                                        </form>
                                    </div>
                                </div>

                                <div class="form-group col-lg-offset-2 col-lg-10">
                                    <div >
                                        <input type="submit" value="Crear" class="btn-azulUCR" id="Create" data-toggle="modal" data-target="#myModal" />
                                        @Html.ActionLink("Cancelar", "Create", "Controller", new { @class = "btn-blancoUCR" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </td>

            <td class="center-block align-middle text-center">
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <button type="button" class="btn btn-primary btn-arrow-left" onclick="addPreguntaToSeccion()">Agregar</button>

            </td>

            <td style="width:60%">
                @Html.Partial("/Views/PreguntaConOpcionesDeSeleccion/_IndexPartial.cshtml", Model.pregunta)

            </td>
        </tr>
    </table>
}

<style>
    .btn-info {
        color: #fff;
        background-color: #41ade7;
    }

    .btn-primary {
        background-color: #f0f0f0;
        color: black;
        border-color: #a2a6aa;
   }

.required:after {
    content: "*";
    font-weight: bold;
    color: red;
}
    .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td 
{
    padding:3%;
}

    .btn {
/* just for this demo. */
   
margin-top: 5px;
}

.btn-arrow-right,
.btn-arrow-left {
   position: relative;
   padding-left: 13px;
   padding-right: 18px;
}

.btn-arrow-right {
   padding-left: 20px;
}

.btn-arrow-left {
   padding-right: 10px;
}

.btn-arrow-right:before,
.btn-arrow-right:after,
.btn-arrow-left:before {
   /* make two squares (before and after), looking similar to the button */
   
   content: "";
   position: absolute;
   top: 5px;
   /* move it down because of rounded corners */
   
   width: 22px;
   /* same as height */
   
   height: 22px;
   /* button_outer_height / sqrt(2) */
   
   background: inherit;
   /* use parent background */
   
   border: inherit;
   /* use parent border */
   
   border-left-color: transparent;
   /* hide left border */
   
   border-bottom-color: transparent;
   /* hide bottom border */
   
   border-radius: 0px 4px 0px 0px;
   /* round arrow corner, the shorthand property doesn't accept "inherit" so it is set to 4px */
   
   -webkit-border-radius: 0px 4px 0px 0px;
   -moz-border-radius: 0px 4px 0px 0px;
}

.btn-arrow-right:before,
.btn-arrow-right:after {
   transform: rotate(45deg);
   /* rotate right arrow squares 45 deg to point right */
   
   -webkit-transform: rotate(45deg);
   -moz-transform: rotate(45deg);
   -o-transform: rotate(45deg);
   -ms-transform: rotate(45deg);
}

.btn-arrow-left:before,
.btn-arrow-left:after {
   transform: rotate(225deg);
   /* rotate left arrow squares 225 deg to point left */
   
   -webkit-transform: rotate(225deg);
   -moz-transform: rotate(225deg);
   -o-transform: rotate(225deg);
   -ms-transform: rotate(225deg);
}

.btn-arrow-right:before,
.btn-arrow-left:before {
   /* align the "before" square to the left */
   
   left: -11px;
}

.btn-arrow-right:after,
.btn-arrow-left:after {
   /* align the "after" square to the right */
   
   right: -11px;
}

.btn-arrow-right:after,
.btn-arrow-left:before {
   /* bring arrow pointers to front */
   
   z-index: 1;
}

.btn-arrow-right:before,
.btn-arrow-left:after {
   /* hide arrow tails background */
   
   background-color: white;
}
</style>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Formularios/AgregarPreguntas.js"></script>
    <script src="~/Scripts/Formularios/ContadorCaracteres.js"></script>
    <script src="~/Scripts/Formularios/DesactivarBotonCrear.js"></script>

    <script>
        $(document).ready(function () {
            validarEntradas();
            agregarPreguntas.init();
            $("#codigotext").attr("disabled", "disabled");
            if ($("input[name=optradio]:checked").val() == "codigoinput") {
                $("#EnterRange").click(function () {
                    $("#codigotext").removeAttr("disabled");
                });
            }
            $('#dtBasicExample').DataTable({
                "ordering": false // false to disable sorting (or any other option)
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>

    @*
        Historia RIP-BKS1
        Se movieron los scripts de la vista parcial a esta vista, porque las vistas
        parciales no pueden tener sus propias secciones (de acuerdo a lo que encontramos).
    *@
    <script type="text/javascript">
        var currentEnabled = null;
        function enableElement(elem) {
            console.log(elem.name);
            if (currentEnabled) {
                currentEnabled.disabled = true;
            }
            elem.disabled = false;
            currentEnabled = elem;
        }
    </script>

    <script type="text/javascript">
        function toggleTextbox(opt) {
            if (opt == 'txtText') {
                var txtPassportNumber = document.getElementById('txtText');
                txtJustificationNumber.disabled = opt.checked ? false : true;
                if (!txtJustificationNumber.disabled) {
                    txtJustificationNumber.focus();
                }
            }

        }

    </script>
}

AppIntegrador/Views/Seccion/Delete.cshtml
@model AppIntegrador.Models.Seccion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Seccion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppIntegrador/Views/Seccion/Edit.cshtml
@model AppIntegrador.Models.Seccion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Seccion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Codigo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-lg-2" })
            <div class="col-lg-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppIntegrador/Views/Seccion/Index.cshtml
@model IEnumerable<AppIntegrador.Models.Seccion>

@{
    ViewBag.Title = "Banco de secciones";
}


<div class="container">
    <h2>Banco de secciones</h2>

    @using (Html.BeginForm(FormMethod.Get))
    {
        <div>
            <div class="card card-default grisUCR2">

                <div class="card-body">
                    <b>
                        Búsqueda:
                    </b>

                    <form action="PreguntaConOpcionesDeSeleccionController/Index" name="opcionfiltro">

                        <select class="form-control my-form-control" id="mySelect" onChange="check(this);">
                            <option value="-">Sin filtro </option>
                            <option value="C">Código </option>
                            <option value="E">Nombre</option>
                        </select>

                        @* campo de filtrado para ingresar el código *@
                        <input class="form-control" type="text" name="input0" placeholder="" id="other-option" style="display:inline;" disabled="true">
                        <input class="form-control" type="text" name="input1" placeholder="Buscar..." id="codigo-option" style="display:none;" maxlength="8">
                        <input class="form-control" type="text" name="input2" placeholder="Buscar..." id="enunciado-option" style="display:none;" maxlength="250">

                        @* Enviar el filtrado al controlador *@
                        <input type="submit"
                               name="submit"
                               value="Filtrar"
                               class="btn" />
                        <br />
                    </form>
                    @if (@ViewBag.filtro != "Ninguno")
                    {
                        <h5><span class="label label-default">@ViewBag.filtro</span></h5>
                    }

                </div>
            </div>
        </div>
    }
    <br />
    <table id="selectedColumn" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%" style=" top: 0; border-collapse: separate;">
        <thead class="thead-dark">
            <tr>
                <th>
                    Código
                </th>
                <th>
                    Nombre
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.ActionLink("Vista previa", "VistaPrevia", new { id = item.Codigo })
                    </td>
                </tr>
            }
    </table>
</div>


<style>
    .test2 {
        background: #fbfbfb;
    }

    input.QuestionCheckbox {
        width: 30px;
        height: 30px;
    }

    .form-control {
        width: 25%;
    }

    .my-form-control {
        width: 10%;
        display: inline
    }

    .btn {
        border: 1px solid #ccc;
    }

    .card-body {
        padding: 10px;
    }
</style>


@section Scripts {

    <script src="~/Scripts/Formularios/Banco.js"></script>

    <script>
        $(document).ready(function () {
            $("#codigotext").attr("disabled", "disabled");
            if ($("input[name=optradio]:checked").val() == "codigoinput") {
                $("#EnterRange").click(function () {
                    $("#codigotext").removeAttr("disabled");
                });
            }
        });
    </script>
    <script>
        function check(elem) 
            // use one of possible conditions
            // if (elem.value == 'Other')
            if (elem.selectedIndex == 0) {
                document.getElementById("other-option").style.display = 'inline';

                document.getElementById("codigo-option").style.display = 'none';
                document.getElementById("codigo-option").value = "";

                document.getElementById("enunciado-option").style.display = 'none';
                document.getElementById("enunciado-option").value = "";
            }
            else if (elem.selectedIndex == 1) {
                document.getElementById("other-option").style.display = 'none';
                document.getElementById("other-option").value = "";

                document.getElementById("codigo-option").style.display = 'inline';

                document.getElementById("enunciado-option").style.display = 'none';
                document.getElementById("enunciado-option").value = "";
            }
            else if (elem.selectedIndex == 2) {
                document.getElementById("other-option").style.display = 'none';
                document.getElementById("other-option").value = "";

                document.getElementById("codigo-option").style.display = 'none';
                document.getElementById("codigo-option").value = "";

                document.getElementById("enunciado-option").style.display = 'inline';
            }
        }
    </script>

    <link href="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.css" rel="stylesheet">

    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>

    <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>

}

AppIntegrador/Views/Seccion/VistaPrevia.cshtml
@model AppIntegrador.Models.Seccion

@{
    ViewBag.Title = "Vista previa";
}

    <div class="container">
        <h4>Vista previa de la sección @Model.Codigo</h4>
        @Html.Action("SeccionConPreguntas", "Seccion", Model.Codigo)
    </div>